apiVersion: v1
kind: Service
metadata:
  name: angular-counter-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: angular-counter-app
  ports:
    - protocol: TCP
      port: 80          # Service port (inside cluster)
      targetPort: 80    # Container port
      nodePort: 32000   # External port on node
